### PR TITLE
Enable auto-publication of CRD to /TR

### PR DESCRIPTION
**Pull request by anssiko**
Adapted from:
https://github.com/w3c/spec-prod/blob/main/docs/examples.md#use-different-respecconfig-when-deploying-to-w3c

Note:
The `ECHIDNA_TOKEN` token needs to be added in the repository Settings: Settings > Security > Secrets and variables > Actions > Repository secrets

Token creation:
https://github.com/w3c/echidna/wiki/Token-creation

### CODE REVIEW

**Review by himorin — APPROVED** [review]
would prefer name as something else (like publication) than CI, but should be fine

**Comment by anssiko** [comment]
@himorin let me know when the ECHIDNA_TOKEN has been set up (I don't have the privileges to do so) and I'll test this workflow in production. 🤞

**Comment by himorin** [comment]
ah, sorry fotgot to mention. it's already installed.

**Comment by anssiko** [comment]
@himorin thank you!

✅ CRD workflow is now operational: https://www.w3.org/TR/vibration/

**Pull request merged**
